<?php
echo "<!DOCTYPE html>\n";
echo "<!-- saved from url=(0026)https://www.scriptyyy.xyz/ -->\n";
echo "<html lang=\"en\" dir=\"ltr\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
echo "\n";
echo "      \n";
echo "      <title>BitMusic&UgolBot</title>\n";
echo "      <link rel=\"stylesheet\" href=\"index.css\">\n";
echo "      <link rel=\"stylesheet\" href=\"all.min.css\">\n";
echo "      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "\n";
echo "      <meta name=\"google-site-verification\" content=\"D8Ytj7P6F7Yt4I2kdtnY8jswMGf4Ra6M932sis1V_T4\" />\n";
echo "   \n";
echo "      <link rel=\"icon\" href=\"favicon.png\">\n";
echo "      <link href=\"css\" rel=\"stylesheet\">\n";
echo "    \n";
echo "      <link href=\"css(1)\" rel=\"stylesheet\">\n";
echo "      \n";
echo "      <link href=\"css(2)\" rel=\"stylesheet\">\n";
echo "\n";
echo "   </head>\n";
echo "   <body onload=\"loaderFunction()\">\n";
echo "\n";
echo "      <div id=\"loader\" style=\"display: none;\">\n";
echo "          <div class=\"loading\">\n";
echo "          <span></span>\n";
echo "          </div>\n";
echo "      </div>\n";
echo "      <div id=\"page\" style=\"display: block;\">\n";
echo "            <nav>\n";
echo "               <div class=\"logo noselect\">\n";
echo "                  <img class=\"noselect\" src=\"favicon.png\"> BitMusic&UgolBot\n";
echo "               </div>\n";
echo "\n";
echo "               <div class=\"openMenu noselect\"><i class=\"\"></i></div>\n";
echo "               <ul class=\"mainMenu noselect\">\n";
echo "                  <li><a class=\"active\" href=\"https://bitmusic.sytes.net\"><i class=\"fas fa-home\"></i> Главная</a></li>\n";
echo "                  <li><a href=\"https://bitmusic.sytes.net/404\"><i class=\"far fa-list-alt\"></i> Команды</a></li>\n";
echo "                  <li><a href=\"https://discord.gg/99pQy4qjKk\" target=\"_none\"><i class=\"\"></i> Поддержка</a></li>\n";
echo "                  <li><a class=\"invite noselect\" href=\"https://discord.com/oauth2/authorize?client_id=857939212442664980&permissions=8&scope=bot\" target=\"_none\"><i class=\"\"></i> Пригласить BitMusic</a></li>\n";
echo "                  <li><a class=\"invite noselect\" href=\"https://discord.com/oauth2/authorize?client_id=893816676376772648&permissions=8&scope=bot\" target=\"_none\"><i class=\"\"></i> Пригласить UgolBot</a></li>\n";
echo "                  <div class=\"closeMenu noselect\"><i class=\"\"></i></div>\n";
echo "               </ul>\n";
echo "         </nav>\n";
echo "\n";
echo "            <div class=\"content noselect\">\n";
echo "               <div class=\"heading text-center\">\n";
echo "                  <h1 class=\"title\">BitMusic</h1>\n";
echo "                  <p class=\"subtitle\">Развеет грусть на вашем сервере.</p>\n";
echo "                  <br>\n";
echo "                  <a class=\"btn btn-primary\" href=\"https://discord.com/oauth2/authorize?client_id=857939212442664980&permissions=8&scope=bot\" target=\"_none\" role=\"button\"><i class=\"\"></i> ПРИГЛАСИТЬ</a>\n";
echo "                  \n";
echo "                  <a class=\"btn btn-secondary\" href=\"https://bitmusic.sytes.net/404\" role=\"button\"><i class=\"\"></i> КОМАНДЫ</a>\n";
echo "               </div>\n";
echo "               <div>\n";
echo "                <div>\n";
echo "                  <h1 class=\"title\">UgolBot</h1>\n";
echo "                  <p class=\"subtitle\">Уберёт всех нарушителей на вашем сервере.</p>\n";
echo "                \n";
echo "                  \n";
echo "                  <br>\n";
echo "                  <a class=\"btn btn-primary\" href=\"https://discord.com/oauth2/authorize?client_id=893816676376772648&permissions=8&scope=bot\" target=\"_none\" role=\"button\"><i class=\"\"></i> ПРИГЛАСИТЬ</a>\n";
echo "                  \n";
echo "                  <a class=\"btn btn-secondary\" href=\"https://bitmusic.sytes.net/404\" role=\"button\"><i class=\"\"></i> КОМАНДЫ</a>\n";
echo "\n";
echo "                  <div>\n";
echo "                  <p>.</p>\n";
echo "                  <div>\n";
echo "\n";
echo "                  <a class=\"btn btn-secondary\" href=\"https://bitmusic.sytes.net/404\" role=\"button\"><i class=\"\"></i> Скачать код страницы</a>\n";
echo "\n";
echo "                  </div>\n";
echo "                  \n";
echo "                  <div>\n";
echo "            </div>   \n";
echo "      </div>\n";
echo "</script>\n";
echo "   \n";
echo "</div></div></body></html>\n";
?>